[package]
name = "advent_of_code_2017"
version = "0.1.0"
authors = ["Galen Elias <gelias@gmail.com>"]

[dependencies]
clap = "*"
regex = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
chrono = "*"

[[bin]]
name = "aoc"
path = "src/main.rs"